library(DESeq2)
data<-read.table("stem_mexpar_count.matrix",header=T,row.names=1)
condition<-c("par_S","par_S","par_S","mex_S","mex_S","mex_S")
cData<-data.frame(TREAT=as.factor(condition))
rownames(cData)<-colnames(data)
d.deseq <- DESeqDataSetFromMatrix(countData = data, colData = cData,design = ~TREAT)
d.deseq <- DESeq(d.deseq)
a<-c("par_S","mex_S")
res <- results(d.deseq,contrast=c("TREAT",a[1],a[2]))
write.table(res,file="stem_mexpar.deseq",sep="\t")
write.table(res,file="stem_mexpar.deseq",sep="\t")